remove_words = ["´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´	",
                "gif"
                "omitted",
                "audio",
                "image",
                "video",
                " ",
                "jjjjj",
                "jajajajajajaja",
                "jajajj",
                "jaja",
                "jajaja",
                "jjjj",
                "jajajajaja",
                "jajajaja",
                "jajajajaa",
                "jajaj",
                "haha",
                "hahaha",
                "lore",
                "im",
                "pm"]